In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
import numpy as np
import time

In [ ]:
data = """"Artificial Intelligence in Healthcare Artificial Intelligence (AI) is playing an increasingly crucial role in transforming healthcare, offering new ways to improve the quality, accessibility, and efficiency of medical services. AI systems, driven by machine learning algorithms, are now capable of processing and analyzing vast datasets far beyond human capacity, enabling quicker and more accurate diagnoses. For example, AI can analyze medical images, such as X-rays, MRIs, and CT scans, to detect anomalies that might be missed by human eyes. This capability is particularly valuable in early diagnosis of diseases such as cancer, where early detection can significantly improve patient outcomesIn addition to diagnostics, AI is being used to personalize treatment plans for patients. By analyzing data from various sources—like electronic health records, genetic information, and lifestyle factors—AI can help clinicians develop individualized treatment strategies that are more effective and have fewer side effects. This personalized approach is at the forefront of what is known as precision medicine, which aims to tailor healthcare to each patient’s unique characteristics.AI is also revolutionizing drug discovery and development. Traditionally, the process of bringing a new drug to market is time-consuming and costly, often taking years and billions of dollars. AI can streamline this process by predicting how different compounds will interact with biological targets, thus identifying potential drug candidates more quickly and at a lower cost. This not only accelerates the development of new treatments but also opens up possibilities for repurposing existing drugs for new uses.Furthermore, AI-powered tools are enhancing the management of chronic diseases. For instance, AI can monitor patients with conditions like diabetes, heart disease, or asthma in real-time, alerting healthcare providers to potential issues before they become critical. These tools can also assist patients in managing their own health by providing reminders to take medication, suggesting dietary adjustments, or recommending physical activities.In hospitals, AI is optimizing operations by automating administrative tasks such as scheduling, billing, and managing patient flow. This not only reduces the workload for healthcare staff but also minimizes errors and improves patient satisfaction by reducing wait times and ensuring that resources are used more efficiently.Another significant application of AI in healthcare is in the field of mental health. AI-based applications can analyze data from a variety of sources, including speech patterns, text messages, and social media activity, to identify signs of mental health issues such as depression or anxiety. These tools can offer support by providing recommendations for interventions or by connecting patients with mental health professionals.Despite the numerous benefits, the integration of AI in healthcare also presents challenges. Data privacy is a major concern, as AI systems require access to sensitive patient information to function effectively. Ensuring that this data is secure and used ethically is paramount. Additionally, there is a need for ongoing training and education for healthcare professionals to effectively use AI tools and to understand their limitations.Moreover, the success of AI in healthcare relies heavily on the quality and diversity of the data it is trained on. Bias in data can lead to biased outcomes, which in turn can affect patient care. Therefore, it is essential to ensure that AI systems are trained on diverse datasets that represent different populations.As AI technology continues to evolve, its potential to transform healthcare is immense. The future of AI in healthcare could include fully automated diagnostic systems, personalized treatment plans generated in real-time, and AI-driven robotic surgeons performing complex procedures with precision that surpasses human capabilities. However, realizing this potential will require collaboration between technologists, healthcare providers, and policymakers to address the challenges and ensure that AI is used in a way that benefits all patients.In conclusion, Artificial Intelligence is set to become a cornerstone of modern healthcare, offering the promise of more efficient, accurate, and personalized care. As we move forward, it will be crucial to balance the benefits of AI with the ethical and practical considerations that come with its integration into healthcare systems."""

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([data])

In [ ]:
input_sequences=[]
for sentence in data.split('.'):
  tokenizer_sentence=tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1,len(tokenizer_sentence)):
    input_sequences.append(tokenizer_sentence[:i+1])

In [ ]:
max_length=max([len(x) for x in input_sequences])
max_length

34

In [ ]:
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_length,padding='pre')
padded_input_sequences

array([[  0,   0,   0, ...,   0,  31,  32],
       [  0,   0,   0, ...,  31,  32,   7],
       [  0,   0,   0, ...,  32,   7,   8],
       ...,
       [  0,   0,   0, ...,  85,  78, 348],
       [  0,   0,   0, ...,  78, 348,   8],
       [  0,   0,   0, ..., 348,   8,  18]], dtype=int32)

In [ ]:
X=padded_input_sequences[:,:-1]
Y=padded_input_sequences[:,-1]

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,  31],
       [  0,   0,   0, ...,   0,  31,  32],
       [  0,   0,   0, ...,  31,  32,   7],
       ...,
       [  0,   0,   0, ...,  17,  85,  78],
       [  0,   0,   0, ...,  85,  78, 348],
       [  0,   0,   0, ...,  78, 348,   8]], dtype=int32)

In [ ]:
Y

array([ 32,   7,   8,  31,  32,   2,   5,  86,  87,  88,  43,  89,   7,
        90,   8,  44,  25,  91,   3,  45,   6,  46,  92,   1,  93,   4,
        47,  94,  18,  48,  11,  95,  96,  97,  19,  98,  99,   4, 100,
         1,  49, 101,  50, 102, 103,  33, 104, 105, 106,   1,  20,  51,
       107, 108,   2,   9,  52,  47, 109,  26,  13, 110, 111, 112,   1,
       113, 114,   3, 115, 116,  10, 117,  53, 118,  11,  33, 119, 120,
         5, 121, 122,   7,  54, 123,   4,  55,  26,  13, 124, 125,  54,
       126,   9, 127,  45,  21, 128, 129,   3, 130,   2,   5, 131,  27,
         3, 132,  34,  56,  12,  22,  49,  16,  57, 133, 134, 135,  23,
       136, 137,  58,   1, 138, 139,   9, 140, 141, 142, 143,  34, 144,
        10,  19,  20, 145,   1, 146, 147, 148, 149,  35, 150,   5,  59,
         6, 151,   4, 152,   5, 153,  13,  60, 154,  61, 155,   3, 156,
         8,   3, 157, 158, 159, 160,   5,  24, 161,  36, 162,   1,  62,
         6,  63,   4, 164,  15,  25,  36,   3, 165,   5,  37, 16

In [ ]:
X.shape,Y.shape

((635, 33), (635,))

In [ ]:
Y=to_categorical(Y,num_classes=len(tokenizer.word_index)+1)

In [ ]:
u=len(tokenizer.word_index)+1
u

349

In [ ]:
Y.shape

(635, 349)

In [ ]:
Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
model=Sequential()
model.add(Embedding(u,100,input_length=max_length))
model.add(LSTM(150))
model.add(Dense(349,activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,Y,epochs=100)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0244 - loss: 5.8323
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0327 - loss: 5.4713
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0497 - loss: 5.3474
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0451 - loss: 5.3103
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0640 - loss: 5.2161
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0517 - loss: 5.1623
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0622 - loss: 5.0828
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0609 - loss: 4.9934
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0665 - loss: 4.8531
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0745 - loss: 4.8223
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0833 - loss: 4.6616
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy:

In [ ]:
test_text="ai"
for i in range(2):
  test_text_padded_squence=tokenizer.texts_to_sequences([test_text])[0]
  test_text_padded_squence=pad_sequences([test_text_padded_squence],maxlen=max_length,padding='pre')
  predicted_word=model.predict(test_text_padded_squence)
  predicted_word=np.argmax(predicted_word)
  for word in tokenizer.word_index.keys():
    if tokenizer.word_index[word]==predicted_word:
      test_text=test_text+" "+word
      break
print(test_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
ai is also
